# @package _global_
measurement_group_name: all

measurements: [
  generalization_dollarstreet, generalization_geode,
  validation_imagenet, generalization_imagenetv2, generalization_imagenetr, generalization_imageneta, generalization_imagenetsketch, generalization_objectnet, 
  ] 
